# Generated by Django 5.0.6 on 2024-05-20 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Concerns", "0003_alter_profile_user_alter_order_user_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
    ]
